# Import node modules
from .nodes import brand_asset_loader
from .nodes import logo_placement_node
from .nodes import logo_overlay_node
from .nodes import solid_color_node
from .nodes import gradient_overlay_node
from .nodes import color_palette_node
from .nodes import global_brand_access
from .nodes import url_image_loader

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(brand_asset_loader.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(logo_placement_node.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(logo_overlay_node.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(solid_color_node.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(gradient_overlay_node.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(color_palette_node.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(global_brand_access.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(url_image_loader.NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(brand_asset_loader.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(logo_placement_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(logo_overlay_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(solid_color_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(gradient_overlay_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(color_palette_node.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(global_brand_access.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(url_image_loader.NODE_DISPLAY_NAME_MAPPINGS)
