# Nodes package for Joshua Brand Assets Loader
# This file makes the nodes directory a Python package

# Import all node modules
from .brand_asset_loader import NODE_CLASS_MAPPINGS as BRAND_LOADER_MAPPINGS
from .brand_asset_loader import NODE_DISPLAY_NAME_MAPPINGS as BRAND_LOADER_DISPLAY_MAPPINGS
from .global_brand_access import NODE_CLASS_MAPPINGS as GLOBAL_ACCESS_MAPPINGS
from .global_brand_access import NODE_DISPLAY_NAME_MAPPINGS as GLOBAL_ACCESS_DISPLAY_MAPPINGS
from .solid_color_node import NODE_CLASS_MAPPINGS as SOLID_COLOR_MAPPINGS
from .solid_color_node import NODE_DISPLAY_NAME_MAPPINGS as SOLID_COLOR_DISPLAY_MAPPINGS
from .gradient_overlay_node import NODE_CLASS_MAPPINGS as GRADIENT_OVERLAY_MAPPINGS
from .gradient_overlay_node import NODE_DISPLAY_NAME_MAPPINGS as GRADIENT_OVERLAY_DISPLAY_MAPPINGS
from .color_palette_node import NODE_CLASS_MAPPINGS as COLOR_PALETTE_MAPPINGS
from .color_palette_node import NODE_DISPLAY_NAME_MAPPINGS as COLOR_PALETTE_DISPLAY_MAPPINGS
from .poi_smart_crop import NODE_CLASS_MAPPINGS as POI_SMART_CROP_MAPPINGS
from .poi_smart_crop import NODE_DISPLAY_NAME_MAPPINGS as POI_SMART_CROP_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {**BRAND_LOADER_MAPPINGS, **GLOBAL_ACCESS_MAPPINGS, **SOLID_COLOR_MAPPINGS, **GRADIENT_OVERLAY_MAPPINGS, **COLOR_PALETTE_MAPPINGS, **POI_SMART_CROP_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BRAND_LOADER_DISPLAY_MAPPINGS, **GLOBAL_ACCESS_DISPLAY_MAPPINGS, **SOLID_COLOR_DISPLAY_MAPPINGS, **GRADIENT_OVERLAY_DISPLAY_MAPPINGS, **COLOR_PALETTE_DISPLAY_MAPPINGS, **POI_SMART_CROP_DISPLAY_MAPPINGS} 